### ISSUE TITLE
crashes when attempting to log events of userscripts running in setupassistant stage

### ISSUE THREAD

**Issue by erikng** [macadmins/installapplications#68]
```
Traceback (most recent call last):
  File "/Library/installapplications/installapplications.py", line 733, in <module>
    main()
  File "/Library/installapplications/installapplications.py", line 700, in main
    iaslog('Detected setupassistant and user script. '
  File "/Library/installapplications/installapplications.py", line 57, in iaslog
    NSLog('[InstallApplications] ' + text)
ValueError: Too few arguments for format string [cur:1/len:1]
```

**Comment by erikng** [comment]
Addressed with https://github.com/macadmins/installapplications/commit/dffbe0a83854bb0df2ae5e6bf55a63034eaa732a
